// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ArticleController from "./article_controller"
import AuthorController from "./author_controller";

application.register("article", ArticleController);
application.register("author", AuthorController);