// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import ApplicationController from "./application_controller";
import { Autocomplete } from "stimulus-autocomplete";
import WelcomeController from "./welcome_controller";
import ArticleController from "./article_controller";
import AuthorController from "./author_controller";
import FlatpickrController from "./flatpickr_controller";
import UserProfileController from "./user_profile_controller";

application.register('application', ApplicationController);
application.register('autocomplete', Autocomplete);
application.register("welcome", WelcomeController);
application.register("article", ArticleController);
application.register("author", AuthorController);
application.register("flatpickr", FlatpickrController);
application.register("userprofile", UserProfileController);
