// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import ApplicationController from "./application_controller";
import { Autocomplete } from "stimulus-autocomplete";
import WelcomeController from "./welcome_controller";
import ArticleController from "./article_controller";
import AuthorController from "./author_controller";
import FlatpickrController from "./flatpickr_controller";
import UserProfileController from "./user_profile_controller";
import ThemeChapterController from "./theme_chapter_controller";
import SearchV1Controller from "./search_v1_controller";
//import DashboardController from "./dashboard_controller";
import SidebarController from "./sidebar_controller";
import CommentController from "./comment_controller";
import CommentReportingController from "./comment_reporting_controller";
import TaggingController from "./tagging_controller";
import ScriptureController from "./scripture_controller";

import AdminAuthorController from "./admin/author_controller";
import AdminContextController from "./admin/context_controller";
import AdminArticleController from "./admin/article_controller";
import AdminTagController from "./admin/tag_controller";
import PanchangTithiController from "./admin/panchang_tithi_controller";
import AdminChapterController from "./admin/chapter_controller";
import AdminScriptureArticleController from "./admin/scripture_article_controller";
import AdmintStrotaArticleController from "./admin/strota_article_controller";
import AdmincompiledScriptureController from "./admin/compiled_scripture_controller";

application.register('application', ApplicationController);
application.register('autocomplete', Autocomplete);
application.register("welcome", WelcomeController);
application.register("article", ArticleController);
application.register("author", AuthorController);
application.register("flatpickr", FlatpickrController);
application.register("userprofile", UserProfileController);
application.register("themechapter", ThemeChapterController);
application.register("search-v1", SearchV1Controller);
application.register("sidebar", SidebarController);
application.register("comment", CommentController);
application.register("comment-reporting", CommentReportingController);
//application.register("dashboard", DashboardController);
application.register("tagging", TaggingController);
application.register("scripture", ScriptureController);

application.register("admin-author", AdminAuthorController);
application.register("admin-context", AdminContextController);
application.register("admin-article", AdminArticleController);
application.register("admin-tag", AdminTagController);
application.register("admin-panchangtithi", PanchangTithiController);
application.register("admin-chapter", AdminChapterController);
application.register("admin-scr-article", AdminScriptureArticleController);
application.register("admin-str-article", AdmintStrotaArticleController);
application.register("admin-cscripture", AdmincompiledScriptureController);
